// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIxxP6aiNSv0fGCSbadSp0bOsKB7bb6A',
    appId: '1:371113582457:web:4ff553820934ec656bd9a8',
    messagingSenderId: '371113582457',
    projectId: 'parking-app-447bd',
    authDomain: 'parking-app-447bd.firebaseapp.com',
    storageBucket: 'parking-app-447bd.firebasestorage.app',
    measurementId: 'G-HG1Q444W17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFV9NTZ3C5qpUoh7LSOJxwSNddCEkvRn4',
    appId: '1:371113582457:android:e5a6fb8519e099736bd9a8',
    messagingSenderId: '371113582457',
    projectId: 'parking-app-447bd',
    storageBucket: 'parking-app-447bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9aPxr2mWsEn__Rn1dZpX6tMXk6xppQo',
    appId: '1:371113582457:ios:b743630df13bea936bd9a8',
    messagingSenderId: '371113582457',
    projectId: 'parking-app-447bd',
    storageBucket: 'parking-app-447bd.firebasestorage.app',
    iosBundleId: 'com.example.parking4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9aPxr2mWsEn__Rn1dZpX6tMXk6xppQo',
    appId: '1:371113582457:ios:b743630df13bea936bd9a8',
    messagingSenderId: '371113582457',
    projectId: 'parking-app-447bd',
    storageBucket: 'parking-app-447bd.firebasestorage.app',
    iosBundleId: 'com.example.parking4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKIxxP6aiNSv0fGCSbadSp0bOsKB7bb6A',
    appId: '1:371113582457:web:cf594041fea237fd6bd9a8',
    messagingSenderId: '371113582457',
    projectId: 'parking-app-447bd',
    authDomain: 'parking-app-447bd.firebaseapp.com',
    storageBucket: 'parking-app-447bd.firebasestorage.app',
    measurementId: 'G-50NY1GP1GN',
  );
}
